### PR TITLE
Closes #73 Clean un DB connections

### LINKED ISSUE #73: Scheduled tasks will not close the connection, causing losing connection to MySQL server during query
According to my observation, each scheduled task will have its own database connection, but it will not close the connection by itself after the task ends. When this number of connections reaches a certain number, the program can no longer create new connections, resulting in the inability to perform subsequent tasks.

2020-05-04 11-45-51 的屏幕截图

### PR DESCRIPTION
**Pull request by missterr**
First of all, thanks for this package! 
This PR solves issue #73. I know you don't use this package anymore and don't review PRs, but this one is pretty simple and maybe you can make an exception. :)

**Description of the problem:**
Django closes the old connection by signals signals.request_started.connect(close_old_connections)
signals.request_finished.connect(close_old_connections) hence apscheduler doesn't do any request, the connections generated by it won't be closed ever.

**Solution:** 
Close connections manually just after each request to DB. In this case, Django will open a new one if required.

### CODE REVIEW

**Comment by jarekwg** [comment]
Hi @missterr,

Thanks for the contribution. Looks sane. I'll merge now, but can't promise on packaging a new version too soon..
I'll try to do that some time this week maybe.

**Comment by LogicJake** [comment]
Thank you all!!!!

**Comment by jarekwg** [comment]
ok 0.3.1 pushed out.

**Comment by missterr** [comment]
Thank you @jarekwg, really appreciate it!

**Pull request merged**
